### ISSUE TITLE
Support for different branches

### ISSUE THREAD

**Issue by igor10k** [jfromaniello/Sublime-Package-Decontrol#1]
For ST3 there are a lot of devs who create another branch where they develop ST3 version of the plugin. So this will be pretty useful.

**Comment by jfromaniello** [comment]
Hi, thanks!, this already works for ST3, check the README:

For **Sublime Text 3** with Python 3.3 install as follows:

> import urllib,urllib.request,os,zipfile; pf='Package Decontrol.sublime-package'; pp=sublime.packages_path(); fp=os.path.join(pp,pf); urllib.request.install_opener(urllib.request.build_opener(urllib.request.ProxyHandler())); open(fp,'wb').write(urllib.request.urlopen('http://bit.ly/s3-package-decontrol').read()); zipfile.ZipFile(fp).extractall(os.path.join(pp, 'Package Decontrol'))

**Comment by igor10k** [comment]
The plugin itself works great. I'm talking about installing other plugins using Package Decontrol. For example, this one https://github.com/lunixbochs/sublimelint . There's a branch **st3** that has ST3 compatible version of the plugin. No way to install it now using Package Decontrol.

**Comment by jfromaniello** [comment]
Now I understand, I just did this on the sublime3 branch... REinstall with the ST3 instructions and then you can install as `lunixbochs/sublimelint#new-python`

**Comment by igor10k** [comment]
So hash sign should be used for branches, thanks. You should probably mention this in the readme :)
