### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by A** [jfromaniello/Sublime-Package-Decontrol#3]
I can install packages from github repo by PC. Why I should use your system?
http://www.macdrifter.com/2012/08/install-sublime-packages-from-github.html

**Comment by jfromaniello** [comment]
Yes, it is almost the same... compared to the steps described in your tutorial you are doing 3 steps where with Package-Decontrol you just have to paste only username/repo (1 step). But I think Package Control also can install from github repositories. 

Also about the update thing of Package Control, I don't quite like how it works, I have had problems in ST2 where Package Control hangs downloading updates and I can't use Sublime for minutes, so I will discourage that thing at least in ST2.

I did this for fun and is working great for me and for other people.  Also Package-Decontrol is few lines of python compared to Package-Control.

So, should you use my system? I don't know use whatever please you
